"""rename department

Revision ID: 46093cbd963c
Revises: 989b61b5fbb9
Create Date: 2024-07-01 20:02:18.053477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46093cbd963c'
down_revision = '989b61b5fbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments','department')
    # ### end Alembic commands ###
